name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Build Docker image
      run: |
        IMAGE_TAG=${GITHUB_SHA}
        docker build . -t ${{ secrets.DOCKER_USERNAME }}/house_image:$IMAGE_TAG

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image
      run: |
        IMAGE_TAG=${GITHUB_SHA}
        docker push ${{ secrets.DOCKER_USERNAME }}/house_image:$IMAGE_TAG

    - name: Tag as latest and push
      run: |
        IMAGE_TAG=${GITHUB_SHA}
        docker tag ${{ secrets.DOCKER_USERNAME }}/house_image:$IMAGE_TAG ${{ secrets.DOCKER_USERNAME }}/my_flask_app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/house_image:latest